// LOCALHOST
### GET ALL CAR COLLECTIONS

GET http://localhost:3000/cars


### Get car collection by id
GET http://localhost:3000/cars/6834268810565735dc6b093e


### Create car collection
POST http://localhost:3000/cars HTTP/1.1
content-type: application/json

  {
  "make": "Toyota",
  "model": "Corolla",
  "year": "two-thosand",
  "color": "Gold",
  "price": "one",
  "mileage": 15000,
  "vin": "2HGFC2F59KH51FTFW1E57PKF1234511234"
  }


### PUT/UPDATE car collection
PUT http://localhost:3000/cars/6834268810565735dc6b093e HTTP/1.1
content-type: application/json

{
    "make": "Toyota",
    "model": "Corolla",
    "year": 1920,
    "color": "123",
    "price": 1,
    "mileage": "1",
    "vin": "1FTFW1E57PKF12345"
}

### DELETE car collection
DELETE http://localhost:3000/cars/683432960210523848fc30ee
