// LOCALHOST
### GET ALL CAR COLLECTIONS

GET http://localhost:3000/cars


### Get car collection by id
GET http://localhost:3000/cars/6834268810565735dc6b093e


### Create car collection
POST http://localhost:3000/cars HTTP/1.1
content-type: application/json

  {
  "make": "Toyota",
  "model": "Corolla",
  "year": "two-thosand",
  "color": "Gold",
  "price": "one",
  "mileage": 15000,
  "vin": "2HGFC2F59KH51FTFW1E57PKF1234511234"
  }


### PUT/UPDATE car collection
PUT http://localhost:3000/cars/6834268810565735dc6b093e HTTP/1.1
content-type: application/json

{
    "make": "Toyota",
    "model": "Corolla",
    "year": 1920,
    "color": "123",
    "price": 1,
    "mileage": "1",
    "vin": "1FTFW1E57PKF12345"
}

### DELETE car collection
DELETE http://localhost:3000/cars/683432960210523848fc30ee



#############################################################################################


### GET ALL CUSTOMER'S DETAILS

GET http://localhost:3000/customers


### Get customers's info by id
GET http://localhost:3000/customers/68374772fd1b5fe25914ec4d


### Create customers's info
POST http://localhost:3000/customers HTTP/1.1
content-type: application/json

  {
  "firstName": "Juan",
  "lastName": "Dela Cruz",
  "phone": "09171234567",
  "email": "juandelacruz@gmail.com",
  "address": "Cebu City",
  "dateOfBirth": "1985-08-15"
  }


### PUT/UPDATE customer's info
PUT http://localhost:3000/customers/68374772fd1b5fe25914ec4d HTTP/1.1
content-type: application/json

{
  "firstName": "Jay",
  "lastName": "Cruz",
    "phone": "09171234123",
  "email": "jaycruz@gmail.com",
  "address": "Cebu City",
  "dateOfBirth": "1985-08-15",
  "preferredContactMethod": "email"
}

### DELETE car collection
DELETE http://localhost:3000/customers/68377062edc09d0eb6e9dc2e